var express = require('express')
var app = express()
app.use(express.json())
const country = require('./routers/country_routes')
const capital= require('./routers/capital_routes')
const city= require('./routers/city_routes')
app.use('/country', country)
app.use('/capital', capital)
app.use('/city', city)
app.listen(3000)
